// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFMS.DAL.Data;

#nullable disable

namespace PFMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240831174750_initial-migration-tables")]
    partial class initialmigrationtables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PFMS.DAL.Entities.TotalTransactionAmount", b =>
                {
                    b.Property<Guid>("TotalTransactionAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("totalTransactionAmountId");

                    b.Property<DateTime>("LastTransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastTransactionDate");

                    b.Property<decimal>("TotalExpence")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalExpence");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalIncome");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("TotalTransactionAmountId");

                    b.HasIndex("UserId");

                    b.ToTable("TotalTransactionAmounts");
                });

            modelBuilder.Entity("PFMS.DAL.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transactionId");

                    b.Property<Guid>("TotalTransactionAmountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("totalTransactionAmountId");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transactionAmount");

                    b.Property<Guid>("TransactionCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transactionCategoryId");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transactionDate");

                    b.Property<string>("TransactionDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transactionDescription");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transactionName");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("transactionType");

                    b.HasKey("TransactionId");

                    b.HasIndex("TotalTransactionAmountId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PFMS.DAL.Entities.TransactionCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("categoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categoryName");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("transactionType");

                    b.HasKey("CategoryId");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("PFMS.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PFMS.DAL.Entities.TotalTransactionAmount", b =>
                {
                    b.HasOne("PFMS.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PFMS.DAL.Entities.Transaction", b =>
                {
                    b.HasOne("PFMS.DAL.Entities.TotalTransactionAmount", "TotalTransactionAmount")
                        .WithMany()
                        .HasForeignKey("TotalTransactionAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PFMS.DAL.Entities.TransactionCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TotalTransactionAmount");

                    b.Navigation("TransactionCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
